In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
l=range(1000)
%timeit [i**2 for i in l]

94.8 μs ± 1.65 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
a=np.arange(1000)
%timeit a**2

1.47 μs ± 22.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
#creating arrays
a = np.array([1,2,3,4])
print(a.ndim)

1


In [9]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.ndim)

2


In [11]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [12]:
print (c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
print(a.shape)

(4,)


In [14]:
print(b.shape)

(2, 3)


In [15]:
print(c.shape)

(2, 2, 2)


# funtions for creating array

In [16]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [18]:
a=np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [19]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [23]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [24]:
print(np.diag(a))

[1 2 3 4]


## Basic Data Types

In [25]:
a=np.arange(10)
print(a.dtype)

int64


In [26]:
a=np.arange(1.0)
print(a.dtype)

float64


In [27]:
a=np.arange(10,dtype="float64")
print(a.dtype)


float64


In [28]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


## OTHER DATATYPE

In [29]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [30]:
a=np.array([True,False])
print(a.dtype)

bool


In [31]:
a=np.array(['srue','alse'])
print(a.dtype)# unicode string type

<U4


## INDEXING AND SLICING

In [32]:
a=np.arange(10)
print(a[5])

5


In [33]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [34]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


## SLICING

In [35]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
print(a[1:8:2])

[1 3 5 7]


In [37]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

## Copies and Viewing

In [38]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [39]:
print(np.shares_memory(a,b))

True


In [40]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [41]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [42]:
print(np.shares_memory(a,b))

False


In [43]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


## Random Number Generator

In [44]:
a=np.random.randint(0,20,15)
print(a)

[17 12  1  3 11 14 12  7 14  4  7  0  5  5  3]


In [45]:
mask=(a%2==0)

In [46]:
mask_a=a[mask]
print(mask_a)

[12 14 12 14  4  0]


In [47]:
a[mask]=-1
print(a)

[17 -1  1  3 11 -1 -1  7 -1 -1  7 -1  5  5  3]


## Element wise Operations

## 1.Basic Operations

In [48]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [49]:
print(a**2)

[ 1  4  9 16]


## All Arithmetic operates Element wise

In [50]:
b=np.ones(4)+1
print("a = ",a)
print("b = ",b)


a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [51]:
print(a*b)

[2. 4. 6. 8.]


In [52]:
print(a-b)

[-1.  0.  1.  2.]


In [53]:
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [54]:
print(c * c)
print("*********************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## Comparison Operators

In [55]:
a=np.array([1,2,3,4])
b=np.array([5,2,7,4])
print(a==b)

[False  True False  True]


In [56]:
print(a<b)

[ True False  True False]


In [57]:
print(a>b)

[False False False False]


In [58]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [59]:
print(np.array_equal(a,c))

True


## Logical Operators

In [60]:
a=np.array([1,0,1,0],dtype = "bool")
b=np.array([1,1,0,0],dtype = "bool")

In [61]:
print(np.logical_or(a,b))

[ True  True  True False]


In [62]:
print(np.logical_and(a,b))

[ True False False False]


## Trigonometry/Transcendental Functions

In [63]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [65]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [66]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
